version: "2"
services:
# this defines a service called app #
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    # this builds the mongo image from the docker repository #
    image: mongo
    # maps the host port to the container port #
    ports:
      - "27017:27017"
